version: '3.5'

networks:
  invoiceplane:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/17

volumes:
  invoiceplane_data:
  nginx_logs:
  mariadb_10_4:

services:
  # --- PHP 8.1
  php:
    container_name: "invoiceplane-php"
    build:
      context: ./resources/docker/php-fpm
      args:
        - PUID=1000
        - PGID=1000
        - TZ=UTC
    links:
      - mariadb_10_4
    expose:
      - "9000"
    dns: 8.8.8.8
    depends_on:
      - mariadb_10_4
    networks:
      invoiceplane:
        ipv4_address: 172.25.0.11
    volumes:
      - ./resources/docker/php-fpm/php.ini:/usr/local/etc/php/php.ini

  # --- nginx 1.23
  nginx:
    container_name: "invoiceplane-nginx"
    build:
      context: ./resources/docker/nginx
    environment:
      - TZ=utc
      - MYSQL_HOST=mariadb_10_4
      - MYSQL_USER=ipdevdb
      - MYSQL_PASSWORD=ipdevdb
      - MYSQL_DB=ipdevdb
      - IP_URL=http://invoiceplane.docker.local
      - DISABLE_SETUP=false
    links:
      - php
    ports:
      - "80:80"
    dns: 8.8.8.8
    depends_on:
      - php
    networks:
      invoiceplane:
        ipv4_address: 172.25.0.12
    volumes:
      - nginx_logs:/var/log/nginx
      - invoiceplane_data:/var/www/html/uploads
      - ./resources/docker/nginx/invoiceplane.conf:/etc/nginx/conf.d/invoiceplane.conf:ro
  mariadb_10_4:
    # MySQL 5.7
    build:
      context: ./resources/docker/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=ipdevdb
      - MYSQL_DATABASE=ipdevdb
      - MYSQL_USER=ipdevdb
      - MYSQL_PASSWORD=ipdevdb
    ports:
      - "3306:3306"
    networks:
      invoiceplane:
        ipv4_address: 172.25.0.13
    volumes:
      - mariadb_10_4:/var/lib/mysql
  phpmyadmin:
    container_name: "invoiceplane-dbadmin"
    build:
      context: ./resources/docker/phpmyadmin
    environment:
      - PMA_HOST=invoiceplane-db
      #- PMA_USER=root
      #- PMA_PASSWORD=ipdevdb
      #- PMA_ROOT_PASSWORD=ipdevdb
      - MYSQL_DATABASE=invoiceplane_db
      - MYSQL_USER=ipdevdb
      - MYSQL_PASSWORD=ipdevdb
      - MYSQL_ROOT_PASSWORD=ipdevdb
      - MAX_EXECUTION_TIME=600
      - MEMORY_LIMIT=256M
      - UPLOAD_LIMIT=2G
    depends_on:
      - mariadb_10_4
    links:
      - mariadb_10_4
    restart: always
    volumes:
      - ./resources/docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - ./resources/docker/databases:/var/www/html/tmp/upload_databases
    ports:
      - "8081:80"
    networks:
      invoiceplane:
        ipv4_address: 172.25.0.16