version: '3.5'

# docker stack deploy --compose-file stack-invoiceplane.yml invoiceplane

volumes:
  invoiceplane_data:
  mariadb_10_4:

services:
  invoiceplane:
    image: mhzawadi/invoiceplane:dev
    volumes:
      - invoiceplane_data:/var/www/html/uploads
    environment:
      - TZ=utc
      - MYSQL_HOST=mariadb_10_4
      - MYSQL_USER=InvoicePlane
      - MYSQL_PASSWORD=invoiceplane
      - MYSQL_DB=InvoicePlane
      - IP_URL=http://invoiceplane.docker.local
      - DISABLE_SETUP=false
    labels:
      - "traefik.http.routers.invoiceplane.rule=Host(`invoiceplane.docker.local`)"
      - "traefik.http.routers.invoiceplane.service=invoiceplane"
      - "traefik.http.services.invoiceplane.loadbalancer.server.port=80"
  mariadb_10_4:
    # MySQL 5.7
    image: mariadb:10.4.10
    volumes:
      - mariadb_10_4:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_password
      - MYSQL_DATABASE=InvoicePlane
      - MYSQL_USER=InvoicePlane
      - MYSQL_PASSWORD=invoiceplane
    labels:
      - "traefik.enable=false"
